#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name": "argocd-cm"}})
---
#@overlay/match missing_ok=True
data:
  configManagementPlugins: |
    - name: ytt
      generate:
        command: ["ytt"]
        args: ["-f", "."]
